---
title       : letterFreq
subtitle    : Developing Data Products
author      : D Bolotov
job         : 
framework   : io2012    # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.jS  # {highlight.js, prettify, highlight}
hitheme     : googlecode          # zenburn tomorrow
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## letterFreq

Ever read some text and wondered what the distribution of characters looks like?

---

## letterFreq

hey there

---

## letterFreq

```{r echo=F}
sanitize <- function(str){
    #input: raw text string
    #output: relative frequencies
    
    str <- substr(str,1,30000)
    
    newstr <- gsub("[^[:alpha:]]", "", str)
    newstr <- tolower(newstr)
    chars <- strsplit(newstr, NULL)[[1]]
    freqs <- summary(factor(chars))
    rfreqs <- freqs / sum(freqs)
    
    return(rfreqs)
}
```

```{r}
str <- "I am a test string with numeric (1234) and other non-alpha characters. (^_^)y "

sanitize(str)

```

---

## letterFreq

Link to shinyapp

The end.




